service: aws-node-scheduled-cron
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  rateHandler:
    handler: index.run
    events:
      # Invoke Lambda function every minute
      - schedule: rate(1 minute)
  cronHandler:
    handler: index.run
    events:
      # Invoke Lambda function every 2nd minute from Mon-Fri
      - schedule: cron(0/2 * ? * MON-FRI *)
